#ifndef LIBQINSTAGRAM_GLOBAL_H
#define LIBQINSTAGRAM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBQINSTAGRAM_LIBRARY)
#  define LIBQINSTAGRAMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBQINSTAGRAMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBQINSTAGRAM_GLOBAL_H
